app:
  port:
  env:

mongo:
  uri: ""
  dbName: ""

jwt:
  secret: ""

cors:
  allowOrigins:
    - "http://"
    - "https://"
  allowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowHeaders:
    - "Origin"
    - "Content-Type"
    - "Authorization"
